### PR TITLE
Parse diffs locally, and other improvements

### LINKED ISSUE #12: Support file moves & renames on the diffparser branch
Currently these modes are not implemented. It would be nice to support them. Currently this is blocking me from merging changes from the diffparser branch.

### PR DESCRIPTION
**Pull request by mystor**
The diffparser branch contains a local diff parser, and other stuff, including:

- [x] Local diff parser, providing more detailed diff understanding #6 
- [x] Specifying projects as reviewers in `r=` #8 
- [x] Support for base revisions on diffs #6 
- [x] Commit authorship & time info for lando #7 
- [x] Accurate mercurial hashes for non-public commits #10 
- [x] Simple mercurial bundle parser to extract changeset details #10 
- [x] Improved binary file support #6 
- [x] Support for moved and copied files in the diff parser #12 
- [x] Support for images & correct MIME types
- [x] Visualization of changes to be sent
- [x] Complete local commit information
- [x] Accurate linting support
- [x] Move/Copy/Multicopy support
- [x] Simplified styling API
- [x] Automatic token login prompt for users without arcanist
- [x] Cleaner revision titles (without r=)
- [x] All diffs uploaded before revisions updated (more atomic commits)
- [x] Improved dependency behaviour (based on push)

Fixes #12, #14, #17, #18, #19, #20

### CODE REVIEW

**Comment by mystor** [comment]
@glandium I haven't had much of a chance to test this branch unfortunately, so I'm not confident merging it yet. Is there any chance you could test it out & let me know if you run into issues?

**Comment by glandium** [comment]
```
  File "/home/glandium/phlay/phlay", line 76
    except IOError, StopIteration:
                  ^
SyntaxError: invalid syntax
```

**Comment by glandium** [comment]
```
Traceback (most recent call last):
  File "/home/glandium/phlay/phlay", line 881, in <module>
    main()
  File "/home/glandium/phlay/phlay", line 873, in main
    process_args(args)
  File "/home/glandium/phlay/phlay", line 806, in process_args
    commit.diff().do_uploads(style, conduit)
  File "/home/glandium/phlay/phlay", line 332, in do_uploads
    for change in self.change.values():
AttributeError: 'Diff' object has no attribute 'change'
```

**Comment by mystor** [comment]
Huh. Not sure how I missed a parse error...
Thanks for pointing out the other error too :-)

**Pull request merged**
